version: "3.6"

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=sample_user
      - POSTGRES_PASSWORD=sample_pwd
      - POSTGRES_DB=sample_project
  web:
    build: .
    container_name: sample_project_backend
    command:
      - /bin/sh
      - -c
      - |
        sleep 10;
        python manage.py collectstatic --no-input
        python manage.py migrate
        python manage.py shell -c "from django.contrib.auth.models import User; \
                     User.objects.filter(username='admin').exists() or \
                     User.objects.create_superuser('admin','admin@example.com', 'admin')"

        gunicorn --workers=1 sample_project.wsgi -b 0.0.0.0:8000
    volumes:
      - static:/home/webapp/sample_project/staticfiles/
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db

  nginx:
    build: ./nginx
    container_name: sample_project_nginx
    volumes:
      - static:/home/webapp/sample_project/staticfiles/
    ports:
      - 5001:80
    depends_on:
      - web

volumes:
  postgres_data:
  static:
